// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.Robot_2015;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontRightoutput2;
    public static SpeedController driveTrainfrontleftoutput3;
    public static SpeedController driveTrainbackrighoutput4;
    public static SpeedController driveTrainbackleftoutput5;
    public static Gyro driveTrainGyro1;
    public static DoubleSolenoid grabDoubleSolenoid1;
    public static DoubleSolenoid grabDoubleSolenoid2;
    public static DoubleSolenoid grabDoubleSolenoid3;
    public static DoubleSolenoid grabDoubleSolenoid4;
    public static AnalogInput liftAnalogInput1;
    public static CANJaguar liftCANJaguar1;
    public static CANJaguar liftCANJaguar2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontRightoutput2 = new Talon(2);
        LiveWindow.addActuator("Drive Train", "Front Right out put 2", (Talon) driveTrainFrontRightoutput2);
        
        driveTrainfrontleftoutput3 = new Talon(3);
        LiveWindow.addActuator("Drive Train", "front left  out put 3", (Talon) driveTrainfrontleftoutput3);
        
        driveTrainbackrighoutput4 = new Talon(4);
        LiveWindow.addActuator("Drive Train", "back righ out put 4", (Talon) driveTrainbackrighoutput4);
        
        driveTrainbackleftoutput5 = new Talon(5);
        LiveWindow.addActuator("Drive Train", "back left output 5", (Talon) driveTrainbackleftoutput5);
        
        driveTrainGyro1 = new Gyro(1);
        LiveWindow.addSensor("Drive Train", "Gyro 1", driveTrainGyro1);
        driveTrainGyro1.setSensitivity(0.007);
        grabDoubleSolenoid1 = new DoubleSolenoid(1, 1, 2);      
        LiveWindow.addActuator("grab", "Double Solenoid 1", grabDoubleSolenoid1);
        
        grabDoubleSolenoid2 = new DoubleSolenoid(0, 2, 3);      
        LiveWindow.addActuator("grab", "Double Solenoid 2", grabDoubleSolenoid2);
        
        grabDoubleSolenoid3 = new DoubleSolenoid(0, 4, 5);      
        LiveWindow.addActuator("grab", "Double Solenoid 3", grabDoubleSolenoid3);
        
        grabDoubleSolenoid4 = new DoubleSolenoid(0, 6, 7);      
        LiveWindow.addActuator("grab", "Double Solenoid 4", grabDoubleSolenoid4);
        
        liftAnalogInput1 = new AnalogInput(0);
        LiveWindow.addSensor("Lift", "Analog Input 1", liftAnalogInput1);
        
        liftCANJaguar1 = new CANJaguar(2);
        
        
        liftCANJaguar2 = new CANJaguar(3);
        
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
